### ISSUE TITLE
After removing battery on ipad. It resprings every time when tried to open control centre.

### ISSUE THREAD

**Issue by AnkitFGM** [Avangelista/StatusMagic#1]
Device : iPad Pro 2020
iPadOS 16.1

**Comment by AnkitFGM** [comment]
Device : ipad pro 2020
iPadOS 16.1

**Comment by Avangelista** [comment]
Thanks for letting me know, I've confirmed this respring happens on simulator as well. Seems to be just iPads. For now just avoid using this setting on iPad.
