### ISSUE TITLE
Breadcrumb function

### ISSUE THREAD

**Issue by All498098** [Avangelista/StatusMagic#10]
My issue is simple I believe, but when overwriting the “breadcrumb” text it works as expected but the function is loss ie apps don’t open when you press BC button maybe it was because I used “” in it I’m not sure

**Comment by Avangelista** [comment]
The app will display your breadcrumb everywhere, UNLESS the system has its own breadcrumb set. Tapping the overridden breadcrumb won't do anything. Tapping the system breadcrumb will take you back to the previous app.
Is this the behaviour you're witnessing, or is there another issue?

**Comment by All498098** [comment]
The problem isn’t the custom name rather I can’t actually launch the app I was last using in tuning iOS 14.8 if that helps

**Comment by Avangelista** [comment]
This may just be a caveat of iOS 14’s system breadcrumb override. Likely no fix planned.
