### ISSUE TITLE
[version 1.0.1] 12 mini, 15.4.1

### ISSUE THREAD

**Issue by Ijustplaymc** [Avangelista/StatusMagic#12]
installed through trollstore, 12 mini 15.4.1

when enabling disable do not disturb, it shows every possible system indicator, instead

Heres what im talking about 

start at bottom

 ![image](https://user-images.githubusercontent.com/98615903/217449502-643d16d3-ae36-4a71-a5f8-5ef516ffde7a.png)

![image](https://user-images.githubusercontent.com/98615903/217449510-25174872-0092-4e14-a3ce-42ca65861a81.png)

![image](https://user-images.githubusercontent.com/98615903/217449522-053b9a7b-cfae-4b11-b5a0-e7441977d3dd.png)

![image](https://user-images.githubusercontent.com/98615903/217449537-ed10251d-1cd9-4e20-bcb6-d996aa33a989.png)

**Comment by Avangelista** [comment]
Ohhhh I think I uploaded the testing build hahahah sorry!!! I’ll post a fix soon.

**Comment by Avangelista** [comment]
Fixed in latest release.

**Comment by cupiditys** [comment]
this should be a real feature though
