### ISSUE TITLE
Disable focus mode icon

### ISSUE THREAD

**Issue by Dr-Sauce** [Avangelista/StatusMagic#19]
Add an option to disable focus mode icon. (It gets squashed)
![New Issue · AvangelistaStatusMagic](https://user-images.githubusercontent.com/82555878/223733672-97f0a306-7109-4cd1-bacc-23063eac5ed1.png)

**Comment by Avangelista** [comment]
The toggle “disable Do Not Disturb” should achieve this.

**Comment by Dr-Sauce** [comment]
Ah! Great. Thanks
