### ISSUE TITLE
Can't patchfind

### ISSUE THREAD

**Issue by Tuchan** [Avangelista/StatusMagic#2]
![image](https://user-images.githubusercontent.com/43300571/216760197-b9596f32-042e-4a2b-a54d-eb65757e4ed5.jpeg)

Installed through ESign (hope that's not the issue)

iPhone 13, 16.1 (20B82)

looking at certain posts, this is happening on 16.1.2 too

**Comment by Avangelista** [comment]
Esign has been known to have issues. Try Sideloadly and see if it persists - if it does, I’ll look into it further.

**Comment by Tuchan** [comment]
yup works, would be cool to add that as a warning in readme
a590f21f934f53a4ee503a668749c0427da065dd

**Comment by ecnivtwelve** [comment]
Hi ! I'm having the same issue using Sideloadly !
(iPhone XR, 16.1.2)

**Comment by 276523923** [comment]
What is your version of ESign?
I'm an ESign developer。

**Comment by Tuchan** [comment]
> What is your version of ESign?


I think I used 4.6.6 here

**Comment by 276523923** [comment]
> > What is your version of ESign?
> 
> I think I used 4.6.6 here

The latest version is 4.7.5. Can you test it？

**Comment by Tuchan** [comment]
> The latest version is 4.7.5. Can you test it？

seems to work without any issues 👍
