### ISSUE TITLE
15.7.3 Not Supported.

### ISSUE THREAD

**Issue by qlife1146** [Avangelista/StatusMagic#22]
I am using iOS 15.7.3(iPhone 7+). When I run the app, I get a notification that it is not supported. The installation was done at altstore.

**Comment by Avangelista** [comment]
15.7.3 is unsupported as the bug this app relies on was patched, as per the description.

**Comment by xerc** [comment]
@Avangelista (did not want to open another ticket)
unfortunately forced - by `Signal` - upgrade from 14 to `15.8.3` [iP:SE]
=> message "not supported" ; means no version above `15.7.2` ?
