### ISSUE TITLE
Carrier name issue 

### ISSUE THREAD

**Issue by lukaschan** [Avangelista/StatusMagic#3]
It would be nice if carrier names could be set differently when 2 sim cards installed.

**Comment by AymenKcm1** [comment]
Came here for this 👍

It only changes the primary SIM carrier name. 

![image](https://user-images.githubusercontent.com/67245917/216792845-feab20bc-4c3c-4bec-9573-78b43c08e4a4.jpeg)

**Comment by Avangelista** [comment]
Ok, I’ll add a fix to the next update.

**Comment by AymenKcm1** [comment]
@Avangelista if you need testing let me know 👍

Thanks 😊

**Comment by Avangelista** [comment]
Fixed in 1.0.1

**Comment by AymenKcm1** [comment]
Thanks 😊 👏👏👏

![image](https://user-images.githubusercontent.com/67245917/217388537-3ad4bd4f-68ae-412e-8b1a-a80b6be3d49b.jpeg)
