### ISSUE TITLE
App says version is not supported despite being vulnerable to MacDirtyCOW

### ISSUE THREAD

**Issue by orangejuliaa** [Avangelista/StatusMagic#5]
Upon opening the app on 16.2 beta, which is vulnerable to MDC in my experience, the app says that the version is not supported and to close the app. I tried changing the iOS version number with Cowabunga, but it still does not work. How could I circumvent this, if possible?

**Comment by sanderDijkxhoorn** [comment]
> Upon opening the app on 16.2 beta, which is vulnerable to MDC in my experience, the app says that the version is not supported and to close the app. I tried changing the iOS version number with Cowabunga, but it still does not work. How could I circumvent this, if possible?

If your beta is actually effected then you could change these values in the sourcecode to add support for your iOS:
https://github.com/Avangelista/StatusMagic/blob/75c4960e9026e9b6985195f66d0a3b2f862b8360/StatusMagic/StatusMagicApp.swift#L19

**Comment by orangejuliaa** [comment]
Thank you. I think it might be a good idea to add some sort of override setting for this to prevent this happening in the future.

**Comment by Avangelista** [comment]
I’ll add a fix for this.
