### ISSUE TITLE
Everything else works. The hidden VPN seems to have failed. It has been tried many times

### ISSUE THREAD

**Issue by sjwjjsw** [Avangelista/StatusMagic#6]
Everything else works. The hidden VPN seems to have failed. It has been tried many times

**Comment by sjwjjsw** [comment]
Everything else works. The hidden VPN seems to have failed. It has been tried many times

**Comment by Avangelista** [comment]
This is a known issue. It will be fixed in the next update within the coming days.

**Comment by sjwjjsw** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by Avangelista** [comment]
Fixed in 1.0.1
